image: maven:3.8.6-amazoncorretto-17

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
              - ./mvnw verify --file pom.xml
            caches:
              - maven
            after-script:
              - pipe: atlassian/checkstyle-report:0.3.0
                variables:
                  DEBUG: "true"
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
  branches:
    master:
      - step:
          name: deploy to docker registry
          script:
            - export IMAGE_NAME=premidel/automatyzacja-repo:$BITBUCKET_COMMIT
            - docker build -t $IMAGE_NAME -f ./docker/Dockerfile .
            - docker login --username $docker_login --password $docker_password
            - docker push $IMAGE_NAME





